name: "actions.mini-program"
description: "integration Mini Program [dev, pub, preview...] with github action, make collaborative development easier"
branding:
  icon: box
  color: green
inputs:
  project_type: 
    description: project type (miniProgram/miniProgramPlugin/miniGame/miniGamePlugin)
    required: true
    default: 'miniProgram'
  action_type:
    description: upload action type 
    required: false
    default: preview
  project_path: 
    description: where the file project.config.json at
    required: false
    default: '' # root dir
  version:
    description: pub version
    required: false
    default: 1.0.0
  ignores:
    description: ignore pub folder
    required: false
    default: dd/dd
  command_options:
    description: compile options # https://developers.weixin.qq.com/miniprogram/dev/devtools/ci.html
    required: false
    default: |
      --project-type=miniProgram
      --upload-description=demo
outputs:
  preview_pic_dir: # id of output
    description: 'the preview qrcode dir'
  source_map_save_path:
    description: source-map-save-path
runs:
  using: "node12"
  main: "./dist/min/index.js"
