name: actions.mini-program
description: integration miniprogram-ci into Github Action, make collaborative development easier
branding:
  icon: box
  color: green
inputs:
  project_type: 
    description: project type (miniProgram/miniProgramPlugin/miniGame/miniGamePlugin)
    required: true
    default: 'miniProgram'
  action_type:
    description: upload action type  (preview/upload/pack-npm/pack-npm-manually/cloud/)
    required: false
    default: preview
  project_path: 
    description: where the file project.config.json at
    required: false
    default: '' # root dir
  version:
    description: pub version
    required: false
    default: 0.0.1
  remark: 
    description: upload version's remark
    required: false
  # ignores:
  #   description: ignore folder
  #   required: false
  subcommand:
    description: 
      in case void miniprogram-cli upgrade to change it's command structure, can use this as subcommand
      values are separated with whitespace
    required: false
  command_options:
    description: compile options # https://developers.weixin.qq.com/miniprogram/dev/devtools/ci.html
    required: false
    default:
      --enable-es6
      --project-ignores=['node_modules/**/*']
outputs:
  preview_pic_dir: # id of output
    description: 'the preview qrcode dir'
  source_map_save_path:
    description: source-map-save-path
runs:
  using: "node12"
  main: "./dist/min/index.js"
